Makefile

fix(makefile): add . before PHONY

---

Cargo.lock
crates/api/Cargo.toml
crates/api/src/chronicle_graphql/query.rs
crates/api/src/lib.rs
crates/common/src/prov/model/to_json_ld.rs
crates/opa-tp-protocol/Cargo.toml
crates/opa-tp-protocol/build.rs
crates/opa-tp-protocol/src/address.rs
crates/opa-tp-protocol/src/client.rs
crates/opa-tp-protocol/src/events.rs
crates/opa-tp-protocol/src/lib.rs
crates/opa-tp-protocol/src/protos/event.proto
crates/opa-tp-protocol/src/protos/submission.proto
crates/opa-tp-protocol/src/sawtooth.rs
crates/opa-tp-protocol/src/state.rs
crates/opa-tp-protocol/src/submission.rs
crates/opa-tp/Cargo.toml
crates/opa-tp/src/abstract_tp.rs
crates/opa-tp/src/main.rs
crates/opa-tp/src/tp.rs
crates/opactl/Cargo.toml
crates/opactl/src/cli.rs
crates/opactl/src/main.rs
crates/sawtooth-tp/Cargo.toml
docs/diagrams/src/chronicle-id.puml
docs/diagrams/src/chronicle-key.puml
docs/diagrams/src/chronicle-opa.puml
mkdocs.yml

An OPA policy and key registration transaction processor, tested at the
protobuf level. Similar in design to the chronicle TP, but should have
no dependencies on the rest of the Chronicle project
Negative / property testing required for cases that cannot be created
with the client message builders.
References:
CHRON-201 CHRON-183
Signed-off-by: Ryan Roberts <ryan.roberts@btp.works>

feat: OPA TP, protocol and skeletal CLI

---

crates/sawtooth-protocol/src/messaging.rs

refactor(sawtooth-protocol): use Handle in submitter submit async block

---

crates/api/src/chronicle_graphql/authorization.rs
crates/api/src/chronicle_graphql/cursor_query.rs
crates/api/src/chronicle_graphql/mod.rs
crates/api/src/lib.rs
crates/chronicle-domain-test/src/test.rs
crates/chronicle/src/bootstrap/cli.rs
crates/chronicle/src/bootstrap/mod.rs
crates/chronicle/src/codegen/linter.rs
crates/common/src/ledger.rs
crates/common/src/prov/id/mod.rs
crates/common/src/prov/model/contradiction.rs
crates/common/src/prov/model/proptest.rs
crates/opa-tp-protocol/src/client.rs
crates/opa-tp-protocol/src/sawtooth.rs
crates/opa-tp-protocol/src/submission.rs
crates/opa-tp/src/tp.rs
crates/sawtooth-protocol/src/messages.rs
crates/sawtooth-protocol/src/messaging.rs

A refactoring intended to change no behavior except to make `cargo` complain less. Addresses CHRON-202 and other issues I noticed.

various code cleanup

---

crates/api/Cargo.toml
crates/chronicle-domain-test/Cargo.toml
crates/chronicle/Cargo.toml

test: fix insta dev-dependency features

---

crates/chronicle-domain-test/Cargo.toml

fix(chronicle-domain-test): add devmode and anonymous-api features

---

docs/cli.md

[CHRON-219](https://blockchaintp.atlassian.net/browse/CHRON-219)
[CHRON-219]: https://blockchaintp.atlassian.net/browse/CHRON-219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(cli): document opa rule and entrypoint args

---

docs/diagrams/include/activity.iuml
docs/diagrams/include/agent.iuml
docs/diagrams/include/entity.iuml
docs/diagrams/src/association.puml
docs/diagrams/src/delegation.puml
docs/diagrams/src/derivation.puml
docs/diagrams/src/primary_source.puml
docs/diagrams/src/publication_as_prov.puml
docs/diagrams/src/question_as_prov.puml
docs/diagrams/src/research_as_prov.puml
docs/diagrams/src/revision_as_prov.puml
docs/diagrams/src/wasQuotedFrom.puml
docs/diagrams/src/was_revision_of.puml
docs/recording_provenance.md
mkdocs.yml

[CHRON-218](https://blockchaintp.atlassian.net/browse/CHRON-218?atlOrigin=eyJpIjoiMTdjZjMwZjQ4Y2VhNGI5NjhkYTAzZmE0ODdmODZlZmMiLCJwIjoiaiJ9)
[CHRON-218]: https://blockchaintp.atlassian.net/browse/CHRON-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: serve mkdocs, align with chronicle-examples diagrams, and fix code blocks

---

docs/recording_provenance.md

describe wasDerivedFrom in docs

---

crates/api/src/chronicle_graphql/mod.rs

Resolves CHRON-231 by making all JWT claims available for OPA rule conditions.

provide JWT claims to OPA policy engine

---

Jenkinsfile
crates/chronicle/src/bootstrap/cli.rs
crates/chronicle/src/bootstrap/mod.rs
docs/cli.md

fix: remove opa cli args and use default allow opa rule

---

crates/common/src/opa_executor.rs

fix: reduce tracing levels in opa

---

Jenkinsfile
docker/chronicle.yaml
docker/unified-builder

Fixes CHRON-228
Signed-off-by: Kevin O'Donnell <kevin.odonnell@btp.works>

fix(docker): correct sawtooth genesis

---

Cargo.lock
Makefile
crates/api/src/chronicle_graphql/activity.rs
crates/chronicle-telemetry/src/telemetry.rs
crates/chronicle/src/bootstrap/mod.rs
crates/common/src/ledger.rs
crates/common/src/opa.rs
crates/common/src/prov/model/contradiction.rs
crates/common/src/prov/model/from_json_ld.rs
crates/opa-tp-protocol/Cargo.toml
crates/opa-tp-protocol/src/events.rs
crates/opa-tp-protocol/src/ledger.rs
crates/opa-tp-protocol/src/lib.rs
crates/opa-tp-protocol/src/sawtooth.rs
crates/opa-tp-protocol/src/state.rs
crates/opa-tp-protocol/src/submission.rs
crates/opa-tp-protocol/src/zmq_client.rs
crates/opa-tp/Cargo.toml
crates/opa-tp/src/abstract_tp.rs
crates/opa-tp/src/lib.rs
crates/opa-tp/src/tp.rs
crates/opactl/Cargo.toml
crates/opactl/src/cli.rs
crates/opactl/src/main.rs
crates/sawtooth-tp/src/abstract_tp.rs
crates/sawtooth-tp/src/tp.rs
docker/unified-builder

* Supports all OPA TP transactions, and provides utility methods for
getting keys and policies
* Can generate keys
* All key material can be supplied by environment variables or files
* Transactor keys are generated on the fly if not supplied
* Sawtooth client traits designed for extraction to new SDK
* ZMQ / Sawtooth simulation layer based on new traits used directly
testing CLI against transaction processor
References: CHRON-208 CHRON-183
Signed-off-by: Ryan Roberts <ryan.roberts@btp.works>

Cli functionality

---

crates/chronicle/src/bootstrap/mod.rs

Retries the PostgreSQL connection, with increasing backoff, then gives up and continues as it would have previously if facing an immediate failure. Resolves CHRON-233.
Developers may prefer to give the `--embedded-database` option to skip the retries and waits.

retry failed database connection

---

mkdocs.yml

docs(mkdocs): update nav links for consistency

---

opa.mk

Removes unnecessary steps that build chronicle/policies that were added in [#208](https://github.com/btpworks/chronicle/pull/208).
[CHRON-259](https://blockchaintp.atlassian.net/browse/CHRON-259)
[CHRON-259]: https://blockchaintp.atlassian.net/browse/CHRON-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove build policies steps from opa.mk

---

Cargo.lock
crates/api/Cargo.toml
crates/chronicle-domain-test/Cargo.toml
crates/chronicle-domain/Cargo.toml
crates/chronicle/Cargo.toml
crates/common/Cargo.toml
crates/common/src/database.rs
crates/opa-tp/Cargo.toml
crates/sawtooth-tp/Cargo.toml

- [RUSTSEC-2021-0141](https://rustsec.org/advisories/RUSTSEC-2021-0141)
- [RUSTSEC-2023-0018](https://rustsec.org/advisories/RUSTSEC-2023-0018)

Fix rust sec vulnerabilities

---

.github/CODEOWNERS

ci(github): correct codeowners

---

crates/common/src/database.rs

Optimistic but easy to try, we can look harder if the error turns up in CI even after this.

attempt retry if embedded PostgreSQL fails unpack

---

crates/common/src/database.rs

fix(database.rs): attempt retry if embedded postgres fails cleanup

---

.pre-commit-config.yaml

Signed-off-by: Kevin O'Donnell <kevin.odonnell@btp.works>

ci(pre-commit): minor fix to forbid-binary

---

Cargo.lock
crates/common/Cargo.toml

[CHRON-271](https://blockchaintp.atlassian.net/browse/CHRON-271)
[CHRON-271]: https://blockchaintp.atlassian.net/browse/CHRON-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: upgrade rust-embed and enable debug-embed feature

---

Makefile

Signed-off-by: Kevin O'Donnell <kevin.odonnell@btp.works>

build(make): publish shouldn't do anything with arm unless releasable

---

.gitignore

fix(gitignore): ignore tar.gz files

---

crates/api/migrations/2023-04-11-111125_generation/down.sql
crates/api/migrations/2023-04-11-111125_generation/up.sql
crates/api/src/persistence/schema.rs
crates/common/src/prov/model/mod.rs
crates/common/src/prov/model/proptest.rs

Fields/columns are unused. Resolves CHRON-285.

simplify Derivation, Generation, Usage

---

.github/workflows/cargo-checkmate.yaml
crates/chronicle/src/bootstrap/mod.rs

fix --inmem build and have CI check it

---

crates/opactl/src/cli.rs

I started out by trying to pass the actual keys on the command line.

have OPA CLI help mention paths more

---

docs/auth.md
docs/cli.md
docs/config.md
docs/opa.md
mkdocs.yml

Addresses CHRON-292 by adding user documentation for the JWT-related configuration.

describe configuration for using authorization server

---

docs/upgrading.md

Bringing `upgrading.md` up to date.
[CHRON-296](https://blockchaintp.atlassian.net/browse/CHRON-296)
[CHRON-296]: https://blockchaintp.atlassian.net/browse/CHRON-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(upgrading): update version upgrade summary

---

docs/opa.md

Completes [CHRON-291](https://blockchaintp.atlassian.net/browse/CHRON-291).
[CHRON-291]: https://blockchaintp.atlassian.net/browse/CHRON-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: complete documenting opactl cli commands

---

docs/cli.md

An oversight in #263's reorganization.

do not list endpoint selection among authentication

---

crates/opactl/src/main.rs
docker/chronicle.yaml

make opactl work

---

docs/opa.md

document how to check OAuth scope with OPA

---

docs/domain_modeling.md

Resolves CHRON-215. Explains how to get Chronicle-specific assistance with VS Code's YAML extension.

describe use of JSON schema in editing domain.yaml

---

charts/chronicle/Chart.yaml
charts/chronicle/templates/statefulset.yaml

fix(charts): add initContainer to correct volume permissions

---

crates/chronicle/src/bootstrap/mod.rs

report better errors at startup

---

crates/api/src/chronicle_graphql/query.rs
crates/chronicle-domain-test/src/test.rs
crates/chronicle/src/codegen/mod.rs
docs/querying_provenance.md

Resolves CHRON-190 and should be non-breaking.

make filter arguments optional for activity timeline query

---

docs/cli.md
docs/recording_provenance.md

Expands information about expected behavior of `import` subcommand.

add note about import data NS does not match CLI NS

---

charts/chronicle/Chart.yaml
charts/chronicle/README.md
charts/chronicle/templates/chronicle-config.yaml
charts/chronicle/templates/chronicle-secret-volume.yaml
charts/chronicle/templates/statefulset.yaml
charts/chronicle/values.yaml

update Chronicle Helm Chart

---

docs/opa.md

[CHRON-343](https://blockchaintp.atlassian.net/browse/CHRON-343)
[CHRON-343]: https://blockchaintp.atlassian.net/browse/CHRON-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: document default OPA policy

---

crates/api/src/lib.rs
docs/namespaces.md

Adds a new built-in namespace for test and other purposes.
chronicle-system, with a fixed uuid
(00000000-0000-0000-0000-000000000001)
Ref: CHRON-342

feat: System namespace

---

Cargo.lock
crates/common/src/ledger.rs
crates/common/src/prov/model/mod.rs
crates/sawtooth-tp/src/abstract_tp.rs
crates/sawtooth-tp/src/tp.rs

Addresses CHRON-346 by adding some explicit logging that appears to cause the spans enclosing them to also log.
Also bumps some logging up to TRACE to reduce risk of leaking PII.

log transaction and effect data better

---

.dockerignore
Makefile
charts/chronicle/Chart.yaml
charts/chronicle/templates/tests/api-test.yaml
charts/chronicle/values.yaml
docker/chronicle-helm-test/subscribe-submit-test
docker/chronicle-helm-test/subscribe-submit-test.dockerfile

To test this without running a full `make build` change the `image` value in `api-test.yaml` to `dev.catenasys.com:8083/chronicle-helm-api-test:latest`. You can also override this value at install time like this:
```bash
helm install test charts/chronicle/ --set test.image.repository='dev.catenasys.com:8083/chronicle-helm-api-test' --set test.image.tag=latest                
```
The container's `command` value can remain the default.
Create a cluster.
```bash
kind create cluster
```
Create the `regcred` Secret (see the `Job` `container` definition, and also [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account) for instructions on adding `ImagePullSecret`s to a service account). This provides your credentials …

test(charts/chronicle): add chronicle api helm chart test

---

crates/api/src/chronicle_graphql/authorization.rs

query userinfo endpoint with HTTP GET, not POST

---

docs/chronicle_vocabulary.md
docs/domain_modeling.md
docs/namespaces.md
docs/recording_provenance.md

better link the namespaces docs page

---

crates/opactl/src/cli.rs
crates/opactl/src/main.rs

Resolves CHRON-362. Adding some log messages seems to have enabled various more from spans.

add logging to opactl

---

crates/common/src/prov/model/from_json_ld.rs
crates/opactl/src/main.rs

Fix/Rust 1.7.0 clippy warnings

---

Cargo.lock
Cargo.toml

chore: Update sawtooth-sdk-rust to hyperledger/main

---

Cargo.lock
crates/opactl/Cargo.toml
crates/opactl/src/cli.rs
crates/opactl/src/main.rs
docs/opa.md

feat: Load policy from remote or path

---

docs/helm-jwks-opa.md
docs/opa.md

Resolves CHRON-357 by bringing into line with #304.

adjust Helm docs to match chart

---

Cargo.lock
Cargo.toml
crates/gq-subscribe/src/main.rs

have gq-ws resolve hostnames

---

docs/helm-jwks-opa.md

update helm docs for OIDC endpoint config

---

docker/unified-builder

Signed-off-by: Kevin O'Donnell <kevin@blockchaintp.com>

fix(docker): always apt-get update to deal with changing repos

---

Makefile

Signed-off-by: Kevin O'Donnell <kevin@blockchaintp.com>

build(make): disable gh release artifact upload

---

docker/unified-builder

build(docker): add wait-for-it script to opactl and opa-tp images

---

crates/common/src/opa.rs
crates/sawtooth-tp/src/tp.rs
docs/opa.md
policies/common_rules.rego

[CHRON-388](https://blockchaintp.atlassian.net/browse/CHRON-388)
[CHRON-388]: https://blockchaintp.atlassian.net/browse/CHRON-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(policies): allow jwt users in default policy

---

docs/helm-jwks-opa.md

if not using auth, we needn't disable OIDC endpoints

---

docs/diagrams/src/oidc-process-jwks.puml
docs/diagrams/src/oidc-process-userinfo.puml
docs/diagrams/src/oidc-process.puml
docs/helm-scenarios.md
docs/oidc-opa-flow.md
mkdocs.yml

Resolves CHRON-396 including documentation for @alexhq and @scealiontach.

expand OIDC and OPA documentation

---

mkdocs.yml

the Chronicle site name should be lower-case

---

docs/auth.md

docs should link to OIDC spec

---

crates/opactl/src/main.rs

fix: File system operations as result / try

---

docs/diagrams/src/oidc-process-jwks.puml
docs/diagrams/src/oidc-process-userinfo.puml
mkdocs.yml

Completes CHRON-396. May assist users checking how Chronicle is interacting with their OIDC server.

add endpoint response caching to flowcharts

---

crates/api/src/chronicle_graphql/authorization.rs
crates/api/src/chronicle_graphql/mod.rs
crates/chronicle/src/bootstrap/cli.rs

Fixes CHRON-398. Useful for providers that issue opaque access tokens.

allow userinfo endpoint to be set without JWKS

---

crates/common/src/identity.rs

Prevent possible leakage of PII.

do not log JWT claim values at WARN level

---

crates/chronicle/src/bootstrap/cli.rs

[CHRON-399](https://blockchaintp.atlassian.net/browse/CHRON-399)
[CHRON-399]: https://blockchaintp.atlassian.net/browse/CHRON-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(bootstrap): add env variable for require-auth cli flag

---

crates/api/src/chronicle_graphql/mod.rs
crates/chronicle-protocol/src/protocol.rs
crates/common/src/identity.rs

* Should reolve sync errors with .6 chains

fix: Handle lack of identity on event

---

docker/unified-builder

Intended to fix current failure of `make build`.

fix circular dependency among Debian packages

---

docs/recording_provenance.md

Resolves CHRON-377 by explaining how to work with immutability.

describe how to record changes without contradiction

---

docs/external-postgres.md
mkdocs.yml

docs(installing): add instructions for using external Postgres db

---

crates/chronicle-synth/generate
crates/chronicle/src/bootstrap/cli.rs
crates/chronicle/src/bootstrap/mod.rs
crates/common/src/import.rs
crates/common/src/lib.rs
crates/common/src/opa.rs
crates/common/src/url.rs
crates/opactl/src/main.rs
docs/cli.md
docs/recording_provenance.md

---
[CHRON-411]: https://blockchaintp.atlassian.net/browse/CHRON-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

load from url support for data import

---

charts/chronicle/Chart.yaml
charts/chronicle/templates/statefulset.yaml

fix(charts): quote postgres password values

---

.github/workflows/cargo-checkmate.yaml

Reverses the no longer needed fix for an issue with cargo checkmate in [PR#181](https://github.com/btpworks/chronicle/pull/181).

install cargo checkmate from crates again

---

crates/chronicle/src/bootstrap/cli.rs
docs/config.md

feat(cli): add env var to set chronicle config file location

---

docker/unified-builder

capture package repository on console

---

crates/api/src/lib.rs
crates/chronicle/src/bootstrap/mod.rs
crates/common/src/identity.rs
crates/common/src/signing.rs
crates/sawtooth-tp/src/tp.rs

[CHRON-446]: https://blockchaintp.atlassian.net/browse/CHRON-446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor(signing): refactor DirectoryStoredKeys chronicle_signing to Fn

---

docs/importing.md
mkdocs.yml

docs(importing): docker-compose import

---

crates/chronicle-protocol/src/lib.rs
crates/chronicle-protocol/src/messages.rs
crates/chronicle-protocol/src/protos/submission.proto
crates/common/src/prov/model/transaction/mod.rs
crates/sawtooth-tp/src/tp.rs

Followup to #392 to complete CHRON-442.

adjust submission protobuf

---

Cargo.lock
Cargo.toml
crates/chronicle/Cargo.toml
crates/chronicle/src/bootstrap/mod.rs

Stabilized in [Rust 1.70.0](https://releases.rs/docs/1.70.0/) #hygiene.

build(bootstrap): use is-terminal now in std lib

---

crates/api/src/lib.rs
crates/api/src/persistence/mod.rs

fix: backport streamlining checks that api calls have effects

---

Cargo.lock
Cargo.toml

removes issue with rustsec-2023-0065

bump poem and tungstenite to latest version

---

COPYRIGHT
crates/chronicle-domain-lint/src/main.rs
crates/chronicle-synth/src/generate.rs
crates/chronicle/src/bootstrap/cli.rs
crates/gq-subscribe/src/main.rs
crates/opa-tp/src/main.rs
crates/opactl/src/cli.rs
crates/sawtooth-tp/src/main.rs
docker/chronicle-test/chronicle-test.dockerfile
docker/opa-builder
docker/opa-test/opa-test.dockerfile
docker/unified-builder

docs: update ownership following IP assignation

---

charts/chronicle/Chart.yaml
charts/chronicle/app-readme.md
charts/chronicle/questions.yaml

refactor: update references in line with move to chronicle(dot)works

---

.github/settings.yml

settings.yml
