- crates/api/src/chronicle_graphql/mod.rs
- crates/api/src/chronicle_graphql/mutation.rs
- crates/api/src/lib.rs
- crates/chronicle-domain-test/src/test.rs
- crates/chronicle/src/bootstrap/mod.rs
- crates/common/src/identity.rs
- crates/common/src/ledger.rs
- crates/common/src/lib.rs
- crates/common/src/protocol.rs
- crates/common/src/prov/model/mod.rs
- crates/sawtooth-protocol/src/messages.rs
- crates/sawtooth-tp/src/tp.rs
Cleans up `common` by moving all `AuthId` code to a separate identity.rs module.
> refactor: move identity to its own module

- Cargo.lock
- component.puml
- crates/api/Cargo.toml
- crates/api/src/chronicle_graphql/authorization.rs
- crates/api/src/chronicle_graphql/mod.rs
- crates/chronicle/Cargo.toml
- crates/chronicle/src/bootstrap/cli.rs
- crates/chronicle/src/bootstrap/mod.rs
- docs/cli.md
Resolves CHRON-204, CHRON-205, CHRON-206, and CHRON-209.
Introduces feature `devmode` that implies both `inmem` and new feature `anonymous-api` which allows unauthenticated access to the GraphQL API by default. Without selecting that feature, the `--anonymous-api` option to `serve-graphql` is required to allow it.
Otherwise, access to the API must now be authenticated: supply instead the `--jwks-address` option with a URI to the keyset used to sign the JWT bearer tokens that one's providing via `Authorization:`. The `--id-pointer` option must be used to provide a JSON pointer into the JWT claims for the Chronicle identity. An `AuthId` bearing the verified external ID can then be found in the GraphQL context.
The Apollo Studio sandbox from `--open` is removed but the Altair GraphQL client …
> Accept and verify JSON web tokens

- Cargo.lock
- crates/chronicle/Cargo.toml
- crates/chronicle/src/bootstrap/cli.rs
- crates/chronicle/src/bootstrap/mod.rs
Ahead of linking up the various Auth elements under development, for developer and user convenience working on Chronicle's `main` branch, in `devmode` initialize the opa-executor in the GraphQL bootstrap with an embedded default allow OPA policy and appropriate entrypoint if no `--opa-rule` and `--opa-entrypoint` args provided. Users in `devmode` can override this feature by providing `--opa-rule` and `--opa-entrypoint` cli args for a given OPA policy.
> fix(chronicle/bootstrap): add embedded default-allow opa rule devmode option 

- crates/chronicle/src/bootstrap/mod.rs
- crates/common/src/opa_executor.rs
> fix(opa_executor): remove unnecessary mutability on opa executor trait

- crates/api/src/chronicle_graphql/mod.rs
- docs/cli.md
Resolves CHRON-227 by relying on OPA to decide on anonymous access. Somebody connecting to the API without an `Authorization:` header is now allowed through with an Anonymous identity in Chronicle.
> Allow anonymous access to API

- crates/api/src/chronicle_graphql/mod.rs
- crates/chronicle/src/bootstrap/cli.rs
- crates/chronicle/src/bootstrap/mod.rs
- docs/cli.md
In researching JWT contents for CHRON-230, I came across consensus that specific claims are well worth checking for expected values, so this PR includes ability to have Chronicle check them accordingly before accepting a JWT. This work is enough separable from the main work for the ticket.
So, for instance, in testing with JWTs from Auth0, one might set `JWT_MUST_CLAIM_ISS` to one's Auth0 tenancy and `JWT_MUST_CLAIM_AUD` to the application API created therein. I also set `JWT_MUST_CLAIM_AZP` to the application's client ID. This is part of ensuring that the JWT was created for the use of Chronicle.
I avoided making any specific check mandatory, to cover for variations in deployment environment.
> allow specification of required JWT claims

- crates/api/src/chronicle_graphql/mod.rs
- crates/chronicle-domain-test/src/test.rs
- crates/common/src/opa_executor.rs
Fixes CHRON-236.
Data set on the GraphQL request in `prepare_request` reaches the handler code's context just fine but not `resolve`'s extension context. Fortunately, for determining a Chronicle ID, it is easy enough to have `OpaCheck` try the JSON pointer separately.
> Correctly pass ID from JWT claims to OPA evaluator

- Cargo.lock
- crates/api/Cargo.toml
- crates/api/src/chronicle_graphql/authorization.rs
- crates/api/src/chronicle_graphql/mod.rs
- crates/chronicle/src/bootstrap/cli.rs
- crates/chronicle/src/bootstrap/mod.rs
- docs/cli.md
Enables optional `--userinfo-address` option which switches behavior to presenting provided bearer token to that endpoint and taking claims as union of those from original token (if not opaque) and those from endpoint (either JWT or plain JSON). Enables CHRON-230 in that scopes may be in access token but user information for deriving Chronicle ID may need requesting separately.
If merged, I'll open a followup ticket for caching the user info so we don't hit the endpoint for every request.
> allow JWT claims to be fleshed out using /userinfo endpoint

- Cargo.lock
- crates/api/Cargo.toml
- crates/api/src/chronicle_graphql/authorization.rs
- crates/api/src/chronicle_graphql/mod.rs
Resolves CHRON-237 by adding caching of responses from when with `--userinfo-address` we pass an access token to an authorization server endpoint to obtain user information for determining the Chronicle ID.
> cache responses from OIDC /userinfo endpoint

- crates/chronicle/src/bootstrap/cli.rs
- crates/chronicle/src/bootstrap/mod.rs
- crates/sawtooth-protocol/src/messaging.rs
- crates/sawtooth-tp/src/main.rs
- crates/sawtooth-tp/src/tp.rs
- make cli args optional for `serve-graphql` subcommands `"jwks-address"` and `"id-pointer"` and change `bootstrap/mod` so that no args for `serve-graphql` subcommands `"jwks-address"` and `"id-pointer"` does not result in a `CliError`
- generate an `Anonymous` agent key if cli args dictate `serve-graphql` user will be `Anonymous`
- revert [change](https://github.com/btpworks/chronicle/pull/171/commits) to `async` block in `submit_sawtooth_tx` (`SawtoothSubmitter::submit`)
- change the policy being bootstrapped in the Sawtooth TP from allow user `Chronicle` to default allow
---
> fix: build - misc

- .cargo/audit.toml
- Cargo.lock
- crates/chronicle/Cargo.toml
- crates/chronicle/src/bootstrap/mod.rs
Replaces use of unmaintained `dotenv` crate with fork `dotenvy`, resolving CHRON-222.
> address RUSTSEC-2021-0141

- crates/chronicle/src/bootstrap/mod.rs
- crates/common/src/database.rs
- docker/unified-builder
To resolve CHRON-248 this generalizes the `pool_remote` retry code into a trait that is also then used before constructing the embedded database pool.
> retry after PgEmbedError PgStartFailure

- README.md
- docs/chronicle_vocabulary.md
- docs/sextant.md
- mkdocs.yml
Tidying up Chronicle first contact experience. Full revision of Chronicle docs to follow.
> docs: shorten readme; move vocabulary into docs; fix sextant page; update index

- Cargo.lock
- Makefile
- crates/chronicle-domain-test/src/test.rs
- crates/chronicle/src/bootstrap/mod.rs
- crates/common/Cargo.toml
- crates/common/benches/opa_executor.rs
- crates/common/build.rs
- crates/common/src/opa.rs
- crates/common/src/policies/auth.rego
- crates/common/src/policies/default_allow.rego
- crates/common/src/policies/default_deny.rego
- crates/sawtooth-tp/src/main.rs
- crates/sawtooth-tp/src/tp.rs
- docker/opa-builder
- docker/unified-builder
- opa.mk
- policies/allow_transactions.rego
- policies/common_rules.rego
This PR makes it possible to use `chronicle-examples` with the most up-to-date Chronicle. 
OPA policies have moved to `/policies` from `/crates/common/policies` and are now built from source via a Makefile directive and distributed in the `unified-builder` to the `chronicle-builder` image.
Building required in order to compile the OPA policies.
See the toolchain and the reorganized policies themselves for the entrypoints being targeted in development.
OPA support and support for embedded policies in bootstrapping and testing has been reorganized around these changes.
Also, worth noting that RustEmbed requires building binaries in `--release` mode. …
> fix: make opa available to chronicle-builder image

- README.md
Early versions of chronicle had an 'infallible' transaction processor in Rust terms - there were no error states and operations would always complete. With the introduction of contradiction this is no longer the case.
> fix: Remove infallible

- crates/api/src/chronicle_graphql/mod.rs
- crates/api/src/chronicle_graphql/mutation.rs
- crates/api/src/lib.rs
- crates/api/src/persistence/mod.rs
- crates/chronicle-domain-test/src/test.rs
- crates/chronicle/src/bootstrap/mod.rs
- crates/common/src/commands.rs
Adds API methods and responses checking whether Chronicle operations resulting from API calls will result in changes in state. If they don't, they won't be submitted to the Transaction Processor and return `Submission::AlreadyRecorded` along with GraphQL data containing `context` and a `null` `tx_id`.
---
[CHRON-146](https://blockchaintp.atlassian.net/browse/CHRON-146)
[CHRON-146]: https://blockchaintp.atlassian.net/browse/CHRON-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> API calls resulting in no data will not be dispatched

- crates/api/src/chronicle_graphql/mod.rs
- crates/chronicle/src/bootstrap/cli.rs
- crates/chronicle/src/bootstrap/mod.rs
- Make setting up access to GraphQL Playground part of no-auth API endpoint path
- Rename `--unlock-cors` to `--playground` while keeping `--open` as a working alias and signal that this flag is now deprecated -- keeping it place for now to ease upgrading `chronicle-examples` for use with latest Chronicle come next release 
[CHRON-270](https://blockchaintp.atlassian.net/browse/CHRON-270)
[CHRON-270]: https://blockchaintp.atlassian.net/browse/CHRON-270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> make graphql playground access part of no auth endpoint

- crates/api/migrations/2022-01-18-144301_ledger_sync/down.sql
- crates/api/migrations/2022-01-18-144301_ledger_sync/up.sql
- crates/api/src/chronicle_graphql/agent.rs
- crates/api/src/chronicle_graphql/entity.rs
- crates/api/src/chronicle_graphql/mutation.rs
- crates/api/src/lib.rs
- crates/api/src/persistence/mod.rs
- crates/api/src/persistence/schema.rs
- crates/chronicle-domain-test/src/test.rs
- crates/chronicle/src/bootstrap/mod.rs
- crates/chronicle/src/codegen/mod.rs
- crates/common/src/commands.rs
- crates/common/src/context.rs
- crates/common/src/ledger.rs
- crates/common/src/prov/id/mod.rs
- crates/common/src/prov/model/from_json_ld.rs
- crates/common/src/prov/model/mod.rs
- crates/common/src/prov/model/proptest.rs
- crates/common/src/prov/model/to_json_ld.rs
- crates/common/src/prov/operations.rs
- crates/common/src/prov/vocab.rs
- domain_docs/attribution.md
- domain_docs/entity_ref.md
- domain_docs/was_attributed_to.md
Add support in Chronicle for [`prov:wasAttributedTo`](https://www.w3.org/TR/prov-o/#wasAttributedTo).
---
Signed-off-by: Joseph Livesey joseph.livesey@btp.works
[CHRON-124](https://blockchaintp.atlassian.net/browse/CHRON-124)
[CHRON-124]: https://blockchaintp.atlassian.net/browse/CHRON-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support prov:wasAttributedTo

- docs/recording_provenance.md
Since @suchapalaver added `Submission::AlreadyRecorded` CHRON-262 noted that the documentation on recording provenance thus required expansion.
> note how a no-op results in no blockchain transaction

- Cargo.lock
- Cargo.toml
- crates/api/Cargo.toml
- crates/async-sawtooth-sdk/Cargo.toml
- crates/chronicle-domain-lint/Cargo.toml
- crates/chronicle-domain-test/Cargo.toml
- crates/chronicle-domain/Cargo.toml
- crates/chronicle-telemetry/Cargo.toml
- crates/chronicle/Cargo.toml
- crates/common/Cargo.toml
- crates/opa-tp-protocol/Cargo.toml
- crates/opa-tp/Cargo.toml
- crates/opactl/Cargo.toml
- crates/sawtooth-protocol/Cargo.toml
- crates/sawtooth-tp/Cargo.toml
- Adds a [dependencies table](https://doc.rust-lang.org/nightly/cargo/reference/workspaces.html#the-dependencies-table) to Chronicle's root Cargo.toml, defining dependencies to be inherited by members of the workspace
- Notes that we currently use different versions of `clap` and `prost` across the workspace
- Bumps dependency versions where no code changes necessary
--- 
[CHRON-273](https://blockchaintp.atlassian.net/browse/CHRON-273)
[CHRON-273]: https://blockchaintp.atlassian.net/browse/CHRON-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add dependencies using workspace dependencies table

- crates/api/src/chronicle_graphql/mod.rs
- crates/chronicle/src/bootstrap/mod.rs
This fixes the issue that if `serve-graphql` can't bind to the socket then Chronicle would just exit without saying why.
It might be worth reviewing the other `.ok()`s in the startup code.
> report any error from starting poem endpoints

- charts/chronicle/templates/statefulset.yaml
- crates/api/src/chronicle_graphql/mod.rs
- crates/api/src/persistence/mod.rs
- crates/api/src/persistence/query.rs
- crates/chronicle/src/bootstrap/cli.rs
- crates/chronicle/src/bootstrap/mod.rs
- crates/common/src/prov/id/mod.rs
- docker/chronicle.yaml
- docs/cli.md
With `serve-graphql` visit http://localhost:9982/data/chronicle:agent:my-agent-id and see JSON summarizing it. (Pipe through `jq .` for prettiness.) Same for activities and entities. Resolves CHRON-277 and CHRON-280.
Substituting `data` with `data/default` works, one may use other namespace IDs for `default`.
Notice that the subcommand has now become `serve-api` with a new `--offer-endpoints` option.
I opted for fairly minimal adjustment of `prov_model_for_namespace` code.
> add endpoint that offers JSON by IRI

- crates/chronicle-domain/Cargo.toml
- crates/opa-tp/Cargo.toml
Placate `cargo checkmate doc` for CHRON-180.
Picked away at these in previous PRs, this fixes remainder, guided by https://github.com/rust-lang/cargo/issues/8898.
> fix docs warnings

- crates/api/src/chronicle_graphql/agent.rs
- crates/api/src/lib.rs
- crates/api/src/persistence/mod.rs
- crates/chronicle-domain-test/src/test.rs
- crates/chronicle/src/bootstrap/mod.rs
- crates/common/src/prov/model/from_json_ld.rs
- crates/common/src/prov/model/mod.rs
- crates/common/src/prov/model/to_json_ld.rs
- crates/common/src/prov/vocab.rs
- crates/sawtooth-tp/src/tp.rs
CHRON-282: the delegate acts on behalf of the responsible agent.
To `ProvModel` this adds `acted_on_behalf` indexed by delegates, complementing `delegation` indexed by responsible agents.
> fix order of delegation participants

- docs/building.md
- docs/cli.md
- docs/domain_modeling.md
- docs/opa.md
- mkdocs.yml
- References to OPA standard
- Explanation of OPA execution in chronicle - GraphQL & TP
- Cookbook style examples of authorization rules
- OPA transaction processor (`opa-tp`) and `opactl`
[CHRON-291](https://blockchaintp.atlassian.net/browse/CHRON-291)
[CHRON-291]: https://blockchaintp.atlassian.net/browse/CHRON-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add opa user documentation

- docs/domain_modeling.md
[CHRON-295](https://blockchaintp.atlassian.net/browse/CHRON-295)
[CHRON-295]: https://blockchaintp.atlassian.net/browse/CHRON-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> document domain definition documentation capabilities

- crates/opa-tp-protocol/src/protos/submission.proto
- crates/opa-tp-protocol/src/submission.rs
- crates/opa-tp-protocol/src/transaction.rs
- crates/opa-tp/src/tp.rs
- crates/opactl/src/cli.rs
- crates/opactl/src/main.rs
- docs/opa.md
Addresses CHRON-213 by adding `--overwrite` to ignore existing keys.
Especially check that the `tp.rs` tests actually test for the desired behavior correctly.
> allow root to re-register user keys

- crates/opactl/src/cli.rs
- crates/opactl/src/main.rs
Has `opactl` not add a blank line if printing new keys to stdout, and not mind trailing blank lines on reading. Previously, `generate` could write data that `register-key` could not read.
> improve opactl whitespace handling with keys

- Cargo.lock
- crates/api/src/chronicle_graphql/mod.rs
- crates/chronicle/src/bootstrap/cli.rs
- crates/chronicle/src/bootstrap/mod.rs
- crates/common/Cargo.toml
- crates/common/src/identity.rs
- crates/common/src/opa.rs
- crates/sawtooth-tp/src/tp.rs
- docs/auth.md
- docs/cli.md
Now, instead of `--id-pointer /sub`, can use `--id-claims iss sub` and the like. As specified in CHRON-246, external IDs are now a SHA-512 hash.
> allow multiple JWT claims to determine ExternalId

- crates/api/src/chronicle_graphql/mod.rs
- crates/api/src/lib.rs
- crates/chronicle/src/bootstrap/cli.rs
- crates/chronicle/src/bootstrap/mod.rs
- docs/cli.md
Resolves CHRON-258.
Allows Chronicle to resolve `localhost` etc. as listening socket(s).
If any of the sockets cannot be bound, the server quits with an error, "Address already in use" or "Permission denied" or whichever is appropriate.
> have --interface option use ToSocketAddrs

- crates/api/src/lib.rs
- crates/async-sawtooth-sdk/src/error.rs
- crates/async-sawtooth-sdk/src/ledger.rs
- crates/async-sawtooth-sdk/src/sawtooth.rs
- crates/async-sawtooth-sdk/src/zmq_client.rs
- crates/chronicle-protocol/src/settings.rs
- crates/common/src/opa.rs
- crates/common/src/prov/model/from_json_ld.rs
- docker/chronicle.yaml
* Retry loops (simple poll) for settings reading and OPA policy load
* Error level traces for timeout / loop
* Ensure we call reconnect on ZmgConnection after timeout or it can
become unusable
* Similar retry loop on event subscription
> fix: Connectivity / startup robustness

- Cargo.lock
- crates/api/Cargo.toml
- crates/api/src/lib.rs
- crates/chronicle/src/bootstrap/cli.rs
- crates/chronicle/src/bootstrap/mod.rs
- crates/common/src/commands.rs
- crates/common/src/prov/operations.rs
- docs/cli.md
- docs/recording_provenance.md
Using Chronicle operations' JSON-LD serialization as an ETL format, this adds an `import` command to Chronicle's CLI that can import Chronicle data stored as a JSON-LD array. For example, here's import data for importing a `CreateNamespace` operation:
```json
[
{
"@id": "_:n1",
"@type": [
"http://btp.works/chronicleoperations/ns#CreateNamespace"
],
"http://btp.works/chronicleoperations/ns#namespaceName": [
{
"@value": "testns"
}
],
"http://btp.works/chronicleoperations/ns#namespaceUuid": [
{
"@value": "6803790d-5891-4dfa-b773-41827d2c630b"
}
]
}
]
```
To try this (assuming you have Postgres set up) copy the above to a file called `import.json` in the Chronicle root directory and run
```bash
cargo run --bin chronicle \
--features inmem \
-- import \
testns \ …
```
> Import Chronicle operations

- crates/common/src/prov/vocab.rs
This came up as a bug during the [work](https://blockchaintp.atlassian.net/browse/CHRON-283) on generating Synth schema. 
> fix(vocab): make ChronicleOperations IRI casing consistent

- crates/chronicle/src/bootstrap/cli.rs
If no private key offered, take public key arg instead for key registration, fits with verifying instead of signing, and with the use of CLAP's `required_unless_present_any`. Fixes CHRON-317.
> fix register-key CLI

- Cargo.lock
- charts/chronicle/app-readme.md
- crates/api/Cargo.toml
- crates/async-sawtooth-sdk/Cargo.toml
- crates/chronicle-domain-lint/Cargo.toml
- crates/chronicle-domain-test/Cargo.toml
- crates/chronicle-domain/Cargo.toml
- crates/chronicle-protocol/Cargo.toml
- crates/chronicle-synth/Cargo.toml
- crates/chronicle-telemetry/Cargo.toml
- crates/chronicle/Cargo.toml
- crates/common/Cargo.toml
- crates/opa-tp-protocol/Cargo.toml
- crates/opa-tp/Cargo.toml
- crates/opactl/Cargo.toml
- crates/sawtooth-tp/Cargo.toml
api@0.7.0
async-sawtooth-sdk@0.7.0
chronicle@0.7.0
chronicle-domain@0.7.0
chronicle-domain-lint@0.7.0
chronicle-example@0.7.0
chronicle-protocol@0.7.0
chronicle-synth@0.7.0
chronicle-telemetry@0.7.0
common@0.7.0
opa-tp@0.7.0
opa-tp-protocol@0.7.0
opactl@0.7.0
sawtooth_tp@0.7.0
Generated by cargo-workspaces
[CHRON-326](https://blockchaintp.atlassian.net/browse/CHRON-326)
[CHRON-326]: https://blockchaintp.atlassian.net/browse/CHRON-326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: bump crate versions to 0.7.0

- Cargo.lock
- crates/api/src/chronicle_graphql/activity.rs
- crates/api/src/chronicle_graphql/mod.rs
- crates/chronicle/src/bootstrap/mod.rs
- crates/common/src/ledger.rs
- crates/common/src/prov/model/contradiction.rs
- crates/common/src/prov/model/from_json_ld.rs
- crates/common/src/prov/model/mod.rs
- crates/sawtooth-protocol/src/events.rs
- crates/sawtooth-protocol/src/messaging.rs
- crates/sawtooth-tp/src/abstract_tp.rs
- crates/sawtooth-tp/src/tp.rs
Observable behaviour from 0-6 logs is a deadlock during mutation after a long idle period.
Deadlock could be reproduced quickly with a chronicle build using a branch of sawtooth-sdk that has a small SyncSender buffer size - the default is 128.
Tokio console indicated that the write task was hung.
sawtooth-sdk-rust will block while attempting to send a message to a saturated SyncSender, holding open a lock which will in turn block the call to send().
The best fix for this scenario is to bring this in line with main - the same ZmqMessageConnection is used for read and write, as the read end will process the unsolicited messages.
* Share the underlying connection via Arc/Mutex , ensuring we empty the SyncStream buffer using the reader side
* Use uuid for correlation id, handles the full type …
> fix: Combine reader/writer

- docker/chronicle-helm-test/subscribe-submit-test
- docker/chronicle-helm-test/subscribe-submit-test.dockerfile
- docker/chronicle-helm-test/wait-for-it
Use the `wait-for-it` script to improve helm test's connection handling.
> test(chronicle-helm-test): include wait-for-it

- .dockerignore
- Cargo.lock
- Cargo.toml
- Makefile
- crates/id-provider/Cargo.toml
- crates/id-provider/src/main.rs
- docker/id-provider-settings.yml
- docker/unified-builder
For the JWKS-enabled Helm testing in CHRON-330 we need a source of verifiable authorization tokens. This PR isn't a proposal for how to include this with Chronicle's testing, it's more a current means to provide the authentication server side for the testing.
Notes on actually using this with `curl` and Chronicle:
1. While the container is running (e.g., during a part of `make test` for this PR) one may `docker exec <container> oauth-token` to obtain a new bearer token arbitrarily many times.
2. Add this token to API requests with some equivalent of curl's `-H "Authorization: Bearer <token>"` filling in the provided token.
3. Forward a local port in Chronicle's container into this new container. That is, Chronicle's `http://localhost:8090/` should reach this container's exposed TCP 8090. …
> build authentication server image

- crates/api/src/lib.rs
- crates/async-sawtooth-sdk/src/ledger.rs
- crates/async-sawtooth-sdk/src/sawtooth.rs
- crates/async-sawtooth-sdk/src/zmq_client.rs
- crates/opactl/src/main.rs
* Ensure Shutdown is sent to ZmqMessageConnection before shutting down tasks to avoid panic
* Use select! and join! to simplify task waiting
* Calculate number of blocks remaining before timeout correctly, and log it
in a readable way
* Log stream completion, no need to handle none with the select!
* Various instrumentation improvements
* Blockid width, warn on parse failiures
* Tested with high concurrency to induce overlapped transaction writes /
waits in multiple clients
Ref: CHRON-358
> fix: Stream completion for opactl / async-sawtooth-sdk

- Cargo.lock
- Cargo.toml
- crates/gq-subscribe/Cargo.toml
- crates/gq-subscribe/src/main.rs
- docker/unified-builder
Assists CHRON-330 by providing a new Rust binary. Example usage:
```
gq-ws -c 2 -s "subscription { commitNotifications { stage delta txId error } }" -t mybearertokenfromoauthtoken
```
It works *only* for subscriptions. The "2" is how many notifications we want reported (I guessed, a submit then a commit). The `-t` argument is optional, it can also do anonymous. `--help` offers a bit more information.
> provide simple tool for authenticated graphql subscriptions

- crates/common/src/ledger.rs
- crates/common/src/prov/model/mod.rs
- crates/sawtooth-tp/src/abstract_tp.rs
- crates/sawtooth-tp/src/tp.rs
Addresses CHRON-346 by adding some explicit logging that appears to cause the spans enclosing them to also log.
Also bumps some logging up to TRACE to reduce risk of leaking PII.
> log transaction and effect data better

- docs/helm-jwks-opa.md
For CHRON-357 we must mention the id-provider used for testing because the pod starts by default and should be disabled in production.
> add information on devIdProvider

- docker/unified-builder
Docker Engine 23.0.1, which currently runs on our CI, has caching that [may misbehave](https://github.com/docker/buildx/issues/1099#issuecomment-1524265654) if `COPY --link` is used because of https://github.com/moby/moby/issues/45111. This PR drops the `--link` as we are using it at the start of the stage anyway and it is not worth tempting fate.
> do not COPY artifacts with --link

- crates/async-sawtooth-sdk/src/error.rs
- crates/async-sawtooth-sdk/src/ledger.rs
- crates/opactl/src/main.rs
* Introduce a resource not found error into SawtoothCommunicationError
* Handle this specifically for get-policy
Ref: CHRON-379
> fix: Exit 0 on no policy found with get-policy

- crates/api/src/chronicle_graphql/authorization.rs
- crates/api/src/chronicle_graphql/mod.rs
The function can verify opaque access tokens as well as JWTs so its name was misleading.
> rename verify_jwt to verify_token

- charts/chronicle/Chart.yaml
- charts/chronicle/templates/_chronicle.tpl
- charts/chronicle/templates/tests/api-test.yaml
dev-id-provider was configuring the JWKS endpoint for `--userinfo-address`. Chart test passed because Chronicle was happy to get a JSON object back.
Having `auth.id.claims: email` would detect this but that's not the best default for normal deployments.
> set dev-id-provider endpoint for userinfo correctly

- crates/api/migrations/2022-01-18-144301_ledger_sync/down.sql
- crates/api/migrations/2023-06-16-145625_attribution_fix/down.sql
- crates/api/migrations/2023-06-16-145625_attribution_fix/up.sql
A previous `up.sql` was edited in #237 to add `attribution`, a mistake that I should have caught. So, some deployments may have the table, some may not. The proper way to do these is shown in #251. Resolves the error in CHRON-408.
> cover for that attribution table may not exist yet

- charts/chronicle/Chart.yaml
- charts/chronicle/templates/test-token-getter-roles.yaml
- charts/chronicle/templates/tests/api-test.yaml
- charts/chronicle/values.yaml
- docs/helm_testing.md
- mkdocs.yml
- If using api-test and `auth.required: true`, if `test.auth.token` provided, the api-test will use the token for the test. 
- If `test.auth.token` is not provided and `auth.required:true` then `devIdProvider` must be enabled.
[CHRON-404](https://blockchaintp.atlassian.net/browse/CHRON-404)
[CHRON-404]: https://blockchaintp.atlassian.net/browse/CHRON-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(charts): allow helm api test to support 3rd party auth service

- docker/opa-builder
- docker/unified-builder
Debian bullseye's ca-certificates-java's post-installation script started failing when installed as a dependency of openjdk-17-jre-headless. Debian bookworm has now been released as the next stable version of Debian, and it does not suffer from that post-installation script bug. Reverts the workaround from #361.
> avoid Debian OpenJDK installation issue

- docker/unified-builder
The stage with the Maven build may be executed more than once so this avoids downloading all the JARs again.
> have maven build share artifact cache

- Cargo.lock
- Cargo.toml
- crates/chronicle-synth/Cargo.toml
- crates/chronicle-synth/src/generate.rs
- crates/chronicle/Cargo.toml
- crates/chronicle/src/bootstrap/mod.rs
- replaces our direct usage of unmaintained `atty` for `is-terminal`
- replaces `structopt` with CLAP v3's `derive` feature
- assists CHRON-419
- uses @suchapalaver's `opa` fix pending CHRON-420
- fixes `cargo audit` failure
> adjust dependencies to improve warnings

- charts/chronicle/Chart.yaml
- charts/chronicle/templates/chronicle-init.yaml
- charts/chronicle/values.yaml
Follows [CHRON-379](https://blockchaintp.atlassian.net/browse/CHRON-379), updating the Helm Chart. Now, when we check if the policy has been set we can simply check if `opactl` output a policy bundle to a file or not.
Requires [#348](https://github.com/btpworks/chronicle/pull/348)
[CHRON-402]: https://blockchaintp.atlassian.net/browse/CHRON-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHRON-379]: https://blockchaintp.atlassian.net/browse/CHRON-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> cleanly check for policy and update to Chronicle v0.7.4

- .cargo/audit.toml
- Cargo.lock
- Cargo.toml
- crates/sawtooth-tp/Cargo.toml
At least since the work on #368 for CHRON-419, these make no difference to `cargo audit`. Also removes `serde_cbor` since #67 and bumps `pest` to v2.7.0.
> no longer ignore some advisories

- charts/chronicle/Chart.yaml
- charts/chronicle/templates/chronicle-init.yaml
Annotation being used is for hooks like tests but this `Job` isn't created by a hook.
This PR uses the [ttl mechanism for finished jobs](https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs).
[CHRON-385](https://blockchaintp.atlassian.net/browse/CHRON-385)
[CHRON-385]: https://blockchaintp.atlassian.net/browse/CHRON-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Helm Chart init Job to delete itself after completing

- crates/api/src/lib.rs
- crates/api/src/persistence/mod.rs
- crates/common/src/prov/operations.rs
I'm going to include a lengthy JSON-LD array of data that can be used to test what this PR does, which is: 
solve a bug discovered through use of Chronicle's `import` feature where Chronicle would attempt to record `EntityDerive` transactions even after they had already been recorded. This is because the `prov_model_for_entity` method for `Store` was not including `Derivation` table data in its reports.
Related PRs include: [#271](https://github.com/btpworks/chronicle/pull/271) and [#213](https://github.com/btpworks/chronicle/pull/213)
- Save the data (it's data for an untyped Chronicle domain) below in a file called `import.json` and put in your Chronicle root directory. 
- Use a database that has not previously recorded the transactions listed below.
- Run:
```bash
RUST_LOG=info \
cargo …
```
> fix(api): include derivation data when fetching provmodel for entity

- Cargo.lock
- crates/api/Cargo.toml
- crates/async-sawtooth-sdk/Cargo.toml
- crates/chronicle-domain-lint/Cargo.toml
- crates/chronicle-domain-test/Cargo.toml
- crates/chronicle-domain/Cargo.toml
- crates/chronicle-protocol/Cargo.toml
- crates/chronicle-synth/Cargo.toml
- crates/chronicle-telemetry/Cargo.toml
- crates/chronicle/Cargo.toml
- crates/common/Cargo.toml
- crates/gq-subscribe/Cargo.toml
- crates/id-provider/Cargo.toml
- crates/opa-tp-protocol/Cargo.toml
- crates/opa-tp/Cargo.toml
- crates/opactl/Cargo.toml
- crates/sawtooth-tp/Cargo.toml
Note that this also bumps `chronicle-telemetry` and `opa-tp` which are not listed as members of the workspace in the root `Cargo.toml`.
> update version numbers to v0.7.5

- docker/helm-api-subscribe-submit-test
- docs/helm_testing.md
Now we have the `"chronicle-system"` namespace let's use it.
[CHRON-449](https://blockchaintp.atlassian.net/browse/CHRON-449)
[CHRON-449]: https://blockchaintp.atlassian.net/browse/CHRON-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> helm api test writes to "chronicle-system" namespace

- docs/helm-jwks-opa.md
- docs/helm-scenarios.md
- docs/helm_testing.md
This resolves [CHRON-426](https://blockchaintp.atlassian.net/browse/CHRON-426) by, as originally suggested by @mtbc , adding documentation that explains default testing settings and requirements when a user provides their own auth endpoints.
[CHRON-426]: https://blockchaintp.atlassian.net/browse/CHRON-426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> helm test blocks install if third party endpoints enabled without a token

- Cargo.lock
- Cargo.toml
- crates/async-sawtooth-sdk/Cargo.toml
- crates/chronicle-domain/Cargo.toml
- crates/chronicle-protocol/Cargo.toml
- crates/chronicle-telemetry/Cargo.toml
- crates/chronicle/Cargo.toml
- crates/common/Cargo.toml
- crates/opa-tp-protocol/Cargo.toml
- crates/opa-tp/Cargo.toml
- crates/sawtooth-tp/Cargo.toml
Using [cargo-udeps](https://crates.io/crates/cargo-udeps) (`cargo install cargo-udeps; cargo +nightly udeps --all-targets`) this removes dependencies detected to be unnecessary with the exception of one returned false positive:
```text
unused dependencies:
`chronicle-telemetry v0.7.5 (/home/joseph/git/btpworks/chronicle/crates/chronicle-telemetry)`
└─── dependencies
└─── "console-subscriber"
Note: They might be false-positive.
```
[CHRON-454]: https://blockchaintp.atlassian.net/browse/CHRON-454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build: remove dependencies unnecessary according to cargo-udeps

- crates/api/src/chronicle_graphql/mutation.rs
- docs/recording_provenance.md
Applies to,
- `startActivity`
- `endActivity`
- `instantActivity`
Addresses CHRON-458 in anticipation of CHRON-185.
Unfortunately, with `async-graphql` generating the schema, I do not see a convenient way of machine-readably marking the parameter as being deprecated.
> deprecate agent: parameter in API

- Cargo.lock
- Cargo.toml
- crates/api/src/chronicle_graphql/mod.rs
- crates/api/src/lib.rs
- crates/api/src/persistence/mod.rs
- crates/async-sawtooth-sdk/src/ledger.rs
- crates/chronicle-domain-test/src/test.rs
- crates/chronicle-protocol/src/messages.rs
- crates/common/src/prov/model/mod.rs
- crates/common/src/prov/model/proptest.rs
- crates/common/src/prov/operations.rs
- crates/sawtooth-tp/src/tp.rs
Picks out additional sleep coverage, as well as adding some itself, and determinism support from [PR 367](https://github.com/btpworks/chronicle/pull/367).
> test: backport sleep coverage and determinism support

- crates/api/src/chronicle_graphql/authorization.rs
Fixes CHRON-460 to match https://docs.btp.works/chronicle/oidc-opa-flow/.
Raises the worrying question of why it was as it was.
> do not tolerate failure response from userinfo endpoint

- charts/chronicle/templates/_chronicle.tpl
- charts/chronicle/templates/statefulset.yaml
- charts/chronicle/values.yaml
- docs/helm-options.md
To test this, run `helm template path/to/chronicle/charts/chronicle` on this Chart, playing with variations in `values.yaml` of:
```yaml
endpoints:
data:
enabled: true
graphql:
enabled: true
```
[CHRON-468]: https://blockchaintp.atlassian.net/browse/CHRON-468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(charts): make offered endpoints explicit in Chronicle Helm Chart

- crates/api/src/lib.rs
- crates/api/src/persistence/mod.rs
Whereas we [were](https://github.com/btpworks/chronicle/pull/213) querying the entire namespace in question when checking whether applying an operation would have effects, we now query much smaller pieces of data to accomplish the same checks. 
Can confirm checking `for i in {1..100}; do cargo run --bin chronicle --features inmem -- perftest 50 60; done
` and the result remained 1 second each time. Prior to these changes we were seeing exponential growth in the elapsed times.
[CHRON-471]: https://blockchaintp.atlassian.net/browse/CHRON-471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(api): streamline checks that api calls have data effects

- Cargo.lock
- Cargo.toml
Addresses RUSTSEC-2023-0052 issue with implicit dependency on `webpki`.
> bump reqwest to current version

- docker/chronicle-test/chronicle-test.dockerfile
- docker/unified-builder
The `setup_lts.x` script is now deprecated, and `graphqurl` seems fine with node v20.
> use node v20 installed via package
